#!/usr/bin/env bash

# install manjaro repo packages
sudo pacman -S \
  alacritty \
  dmenu \
  docker \
  docker-compose \
  feh \
  git \
  parcellite \
  pdfgrep \
  ruby \
  slock \
  trayer \
  tree \
  vim \
  xsel \
  xss-lock \
  yay \
  zsh

# install aur packages
yay -S antibody handlr-bin ripgrep

# install colours
git clone https://github.com/dkeg/crayolo.git ~/crayolo

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

# set zsh as default shell
chsh -s /bin/zsh
