#!/usr/bin/env bash

# install manjaro packages
sudo pacman -S \
  alacritty \
  blueberry \
  dmenu \
  docker \
  docker-compose \
  feh \
  fish \
  git \
  gnome-screenshot
  mpv \
  network-manager-applet \
  numlockx \
  pamac-all \
  parcellite \
  pavucontrol \
  pdfgrep \
  polkit-gnome \
  polkit\
  ruby \
  slock \
  streamlink \
  tldr \
  tree \
  vim \
  xfce4-notifyd \
  xfce4-power-manager \
  xreader \
  xsel \
  xss-lock \
  yay

# install aur packages
yay -S \
  fd \
  gsimplecal \
  handlr-bin \
  picom \
  ripgrep \
  sxhkd \
  termite \
  thunar \
  variety \
  volumeicon \
  xfce4-taskmanager

# set fish as default shell
chsh -s /bin/fish
