# wallust v3.5

backend = "fastresize"
color_space = "salience"
palette = "saliencedark"

[templates]
# write to pywal cache directory for compatibility
alacritty-nodim = { template = 'colors-nodim-alacritty.toml', target = '/home/thomas/.cache/wal/colors-nodim-alacritty.toml' }
alacritty = { template = 'colors-alacritty.yml', target = '/home/thomas/.cache/wal/colors-alacritty.yml' }
ghostty = { template = 'colors.ghostty', target = '/home/thomas/.cache/wal/colors.ghostty' }
fish = { template = 'colors.fish', target = '/home/thomas/.cache/wal/colors.fish' }
shell = { template = 'colors.sh', target = '/home/thomas/.cache/wal/colors.sh' }
dunst = { template = 'dunstrc', target = '/home/thomas/.cache/wal/dunstrc' }
dwm = { template = 'colors-wal-dwm.h', target = '/home/thomas/.cache/wal/colors-wal-dwm.h' }
vim = { template = 'colors-wal.vim', target = '/home/thomas/.cache/wal/colors-wal.vim' }
json = { template = 'colors.json', target = '/home/thomas/.cache/wal/colors.json' }
sequences = { template = 'sequences', target = '/home/thomas/.cache/wal/sequences' }
test = { template = 'test.toml', target = '/tmp/wallust-test-output.toml' }
